from database.models import FuturesProductBean


class FuturesProductInfoUtils:
    future_list = [
        {'pinYin': 'HJ', 'tradingCode': 'AU', 'tradingProduct': '沪金', 'tradingUnits': '1000', 'minimumPriceChange': '0.02', 'marginRatio': '8'},
        {'pinYin': 'HY', 'tradingCode': 'AG', 'tradingProduct': '沪银', 'tradingUnits': '15', 'minimumPriceChange': '1', 'marginRatio': '10'},
        {'pinYin': 'HT', 'tradingCode': 'CU', 'tradingProduct': '沪铜', 'tradingUnits': '5', 'minimumPriceChange': '10', 'marginRatio': '8'},
        {'pinYin': 'HL', 'tradingCode': 'AL', 'tradingProduct': '沪铝', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '8'},
        {'pinYin': 'HX', 'tradingCode': 'ZN', 'tradingProduct': '沪锌', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '8'},
        {'pinYin': 'HQ', 'tradingCode': 'PB', 'tradingProduct': '沪铅', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '8'},
        {'pinYin': 'HN', 'tradingCode': 'NI', 'tradingProduct': '沪镍', 'tradingUnits': '1', 'minimumPriceChange': '10', 'marginRatio': '12'},
        {'pinYin': 'HX', 'tradingCode': 'SN', 'tradingProduct': '沪锡', 'tradingUnits': '1', 'minimumPriceChange': '10', 'marginRatio': '12'},
        {'pinYin': 'YHL', 'tradingCode': 'AO', 'tradingProduct': '氧化铝', 'tradingUnits': '20', 'minimumPriceChange': '1', 'marginRatio': '9'},
        {'pinYin': 'GJT', 'tradingCode': 'BC', 'tradingProduct': '国际铜', 'tradingUnits': '5', 'minimumPriceChange': '10', 'marginRatio': '8'},
        {'pinYin': 'GYG', 'tradingCode': 'SI', 'tradingProduct': '工业硅', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '9'},
        {'pinYin': 'TSL', 'tradingCode': 'LC', 'tradingProduct': '碳酸锂', 'tradingUnits': '1', 'minimumPriceChange': '50', 'marginRatio': '9'},
        {'pinYin': 'LWG', 'tradingCode': 'RB', 'tradingProduct': '螺纹钢', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '7'},
        {'pinYin': 'TKS', 'tradingCode': 'I', 'tradingProduct': '铁矿石', 'tradingUnits': '100', 'minimumPriceChange': '0.5', 'marginRatio': '13'},
        {'pinYin': 'RJ', 'tradingCode': 'HC', 'tradingProduct': '热卷', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '7'},
        {'pinYin': 'BXG', 'tradingCode': 'SS', 'tradingProduct': '不锈钢', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '7'},
        {'pinYin': 'XC', 'tradingCode': 'WR', 'tradingProduct': '线材', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '9'},
        {'pinYin': 'GT', 'tradingCode': 'SF', 'tradingProduct': '硅铁', 'tradingUnits': '5', 'minimumPriceChange': '2', 'marginRatio': '12'},
        {'pinYin': 'MG', 'tradingCode': 'SM', 'tradingProduct': '锰硅', 'tradingUnits': '5', 'minimumPriceChange': '2', 'marginRatio': '12'},
        {'pinYin': 'JM', 'tradingCode': 'JM', 'tradingProduct': '焦煤', 'tradingUnits': '60', 'minimumPriceChange': '0.5', 'marginRatio': '20'},
        {'pinYin': 'JT', 'tradingCode': 'J', 'tradingProduct': '焦炭', 'tradingUnits': '100', 'minimumPriceChange': '0.5', 'marginRatio': '20'},
        {'pinYin': 'BL', 'tradingCode': 'FG', 'tradingProduct': '玻璃', 'tradingUnits': '20', 'minimumPriceChange': '1', 'marginRatio': '9'},
        {'pinYin': 'ZJ', 'tradingCode': 'SP', 'tradingProduct': '纸浆', 'tradingUnits': '10', 'minimumPriceChange': '2', 'marginRatio': '8'},
        {'pinYin': 'YY', 'tradingCode': 'SC', 'tradingProduct': '原油', 'tradingUnits': '1000', 'minimumPriceChange': '0.1', 'marginRatio': '10'},
        {'pinYin': 'RLY', 'tradingCode': 'FU', 'tradingProduct': '燃料油', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '12'},
        {'pinYin': 'LURLY', 'tradingCode': 'LU', 'tradingProduct': 'LU燃料油', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '12'},
        {'pinYin': 'LQ', 'tradingCode': 'BU', 'tradingProduct': '沥青', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '10'},
        {'pinYin': 'YHQ', 'tradingCode': 'PG', 'tradingProduct': 'LPG', 'tradingUnits': '20', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'PTA', 'tradingCode': 'TA', 'tradingProduct': 'PTA', 'tradingUnits': '5', 'minimumPriceChange': '2', 'marginRatio': '7'},
        {'pinYin': 'PVC', 'tradingCode': 'V', 'tradingProduct': 'PVC', 'tradingUnits': '5', 'minimumPriceChange': '1', 'marginRatio': '7'},
        {'pinYin': 'BRXJ', 'tradingCode': 'BR', 'tradingProduct': '合成橡胶', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '7'},
        {'pinYin': 'XJ', 'tradingCode': 'RU', 'tradingProduct': '橡胶', 'tradingUnits': '10', 'minimumPriceChange': '5', 'marginRatio': '10'},
        {'pinYin': '20HJ', 'tradingCode': 'NR', 'tradingProduct': '20号胶', 'tradingUnits': '10', 'minimumPriceChange': '5', 'marginRatio': '8'},
        {'pinYin': 'SL', 'tradingCode': 'L', 'tradingProduct': '塑料', 'tradingUnits': '5', 'minimumPriceChange': '1', 'marginRatio': '7'},
        {'pinYin': 'DX', 'tradingCode': 'PF', 'tradingProduct': '短纤', 'tradingUnits': '5', 'minimumPriceChange': '2', 'marginRatio': '8'},
        {'pinYin': 'YEC', 'tradingCode': 'EG', 'tradingProduct': '乙二醇', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'JC', 'tradingCode': 'MA', 'tradingProduct': '甲醇', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'JBX', 'tradingCode': 'PP', 'tradingProduct': '聚丙烯', 'tradingUnits': '5', 'minimumPriceChange': '1', 'marginRatio': '7'},
        {'pinYin': 'BBX', 'tradingCode': 'EB', 'tradingProduct': '苯乙烯', 'tradingUnits': '5', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'NS', 'tradingCode': 'UR', 'tradingProduct': '尿素', 'tradingUnits': '20', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'CJ', 'tradingCode': 'SA', 'tradingProduct': '纯碱', 'tradingUnits': '20', 'minimumPriceChange': '1', 'marginRatio': '9'},
        {'pinYin': 'DEJB', 'tradingCode': 'PX', 'tradingProduct': '对二甲苯', 'tradingUnits': '5', 'minimumPriceChange': '2', 'marginRatio': '12'},
        {'pinYin': 'SJ', 'tradingCode': 'SH', 'tradingProduct': '烧碱', 'tradingUnits': '30', 'minimumPriceChange': '1', 'marginRatio': '5'},
        {'pinYin': 'YM', 'tradingCode': 'C', 'tradingProduct': '玉米', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'DY', 'tradingCode': 'A', 'tradingProduct': '豆一', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'DF', 'tradingCode': 'CS', 'tradingProduct': '淀粉', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '6'},
        {'pinYin': 'DE', 'tradingCode': 'B', 'tradingProduct': '豆二', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'DP', 'tradingCode': 'M', 'tradingProduct': '豆粕', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '7'},
        {'pinYin': 'DY', 'tradingCode': 'Y', 'tradingProduct': '豆油', 'tradingUnits': '10', 'minimumPriceChange': '2', 'marginRatio': '7'},
        {'pinYin': 'YCZ', 'tradingCode': 'RS', 'tradingProduct': '油菜籽', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '20'},
        {'pinYin': 'YCZ', 'tradingCode': 'RM', 'tradingProduct': '菜粕', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '9'},
        {'pinYin': 'CZY', 'tradingCode': 'OI', 'tradingProduct': '菜油', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '9'},
        {'pinYin': 'ZLY', 'tradingCode': 'P', 'tradingProduct': '棕榈油', 'tradingUnits': '10', 'minimumPriceChange': '2', 'marginRatio': '8'},
        {'pinYin': 'HS', 'tradingCode': 'PK', 'tradingProduct': '花生', 'tradingUnits': '5', 'minimumPriceChange': '2', 'marginRatio': '8'},
        {'pinYin': 'MH', 'tradingCode': 'CF', 'tradingProduct': '棉花', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '7'},
        {'pinYin': 'BT', 'tradingCode': 'SR', 'tradingProduct': '白糖', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '7'},
        {'pinYin': 'MS', 'tradingCode': 'CY', 'tradingProduct': '棉纱', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '7'},
        {'pinYin': 'JD', 'tradingCode': 'JD', 'tradingProduct': '鸡蛋', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '8'},
        {'pinYin': 'SZ', 'tradingCode': 'LH', 'tradingProduct': '生猪', 'tradingUnits': '16', 'minimumPriceChange': '5', 'marginRatio': '12'},
        {'pinYin': 'PG', 'tradingCode': 'AP', 'tradingProduct': '苹果', 'tradingUnits': '10', 'minimumPriceChange': '1', 'marginRatio': '10'},
        {'pinYin': 'HZ', 'tradingCode': 'CJ', 'tradingProduct': '红枣', 'tradingUnits': '5', 'minimumPriceChange': '5', 'marginRatio': '12'},
        {'pinYin': 'JYOX', 'tradingCode': 'EC', 'tradingProduct': '集运欧线', 'tradingUnits': '50', 'minimumPriceChange': '0.1', 'marginRatio': '12'},
    ]

def dict_to_futures_product_bean(data):
    return FuturesProductBean(
        pin_yin=data['pinYin'],
        trading_product=data['tradingProduct'],
        trading_code=data['tradingCode'],
        trading_units=float(data['tradingUnits']),
        minimum_price_change=float(data['minimumPriceChange']),
        margin_ratio=float(data['marginRatio'])
    )


