# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ths_helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(744, 60)
        Dialog.setMinimumSize(QtCore.QSize(600, 60))
        Dialog.setMaximumSize(QtCore.QSize(1200, 60))
        self.pushButton_ChatInvert = QtWidgets.QPushButton(Dialog)
        self.pushButton_ChatInvert.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ChatInvert.setFont(font)
        self.pushButton_ChatInvert.setObjectName("pushButton_ChatInvert")
        self.pushButton_PageUp = QtWidgets.QPushButton(Dialog)
        self.pushButton_PageUp.setGeometry(QtCore.QRect(140, 10, 140, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_PageUp.setFont(font)
        self.pushButton_PageUp.setObjectName("pushButton_PageUp")
        self.pushButton_PageDown = QtWidgets.QPushButton(Dialog)
        self.pushButton_PageDown.setGeometry(QtCore.QRect(290, 10, 140, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_PageDown.setFont(font)
        self.pushButton_PageDown.setObjectName("pushButton_PageDown")
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(570, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_pankou = QtWidgets.QPushButton(Dialog)
        self.pushButton_pankou.setGeometry(QtCore.QRect(440, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_pankou.setFont(font)
        self.pushButton_pankou.setObjectName("pushButton_pankou")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_ChatInvert.setText(_translate("Dialog", "图表反转"))
        self.pushButton_PageUp.setText(_translate("Dialog", "翻页（上）"))
        self.pushButton_PageDown.setText(_translate("Dialog", "翻页（下）"))
        self.pushButton_close.setText(_translate("Dialog", "关 闭"))
        self.pushButton_pankou.setText(_translate("Dialog", "盘 口"))
